// web/src/components/FilterBar.tsx
import { useFilterStore } from '../store'
import { makerCounts, yearCounts } from '../lib/filter'
import type { WorkRow } from '../lib/parse'
import MultiSelect from './MultiSelect'

/**
 * 筛选工具栏：人物多选（可选）+ 厂商多选 + 关键词 + 年份 + 时长 + 排序 + 合并BD + 重置 + 导出。
 * 年份选项从传入的基准行里推导（人物页 = 该人物全部记录；全部作品页 = 当前选中人物的记录）。
 */
export default function FilterBar({
  baseRows, showActorSort, onExport
}: {
  baseRows: WorkRow[]
  /** 显示“人物”排序选项（多人物对比时才有意义） */
  showActorSort?: boolean
  onExport?: () => void
}) {
  const s = useFilterStore()
  const years = yearCounts(baseRows).map(([y]) => y).reverse()

  return (
    <div className="card fade-up relative z-10 p-4 md:p-5">
      <div className="grid gap-2.5 md:grid-cols-2">
        <MakerOpts baseRows={baseRows} />
      </div>

      <div className="mt-3 flex flex-wrap items-center gap-2 border-t border-dashed border-[var(--line)] pt-3">
        <input
          type="search"
          value={s.kw}
          onChange={e => s.setKw(e.target.value)}
          placeholder="搜索番号或厂商…"
          className="input search-input min-w-[160px] flex-[1_1_170px]"
        />
        <select className="input" value={s.year} onChange={e => s.setYear(e.target.value)}>
          <option value="">全部年份</option>
          {years.map(y => <option key={y} value={y}>{y} 年</option>)}
        </select>
        <select className="input" value={s.minLen} onChange={e => s.setMinLen(Number(e.target.value))}>
          <option value={0}>全部时长</option>
          <option value={120}>≥120 分</option>
          <option value={240}>≥240 分</option>
          <option value={480}>≥480 分</option>
          <option value={960}>≥960 分</option>
        </select>
        <select
          className="input"
          value={`${s.sortKey}:${s.sortDir}`}
          onChange={e => {
            const [k, d] = e.target.value.split(':')
            useFilterStore.setState({ sortKey: k as typeof s.sortKey, sortDir: Number(d) as typeof s.sortDir })
          }}
        >
          <option value="date:-1">发行 ↓ 新→旧</option>
          <option value="date:1">发行 ↑ 旧→新</option>
          <option value="code:1">番号 A→Z</option>
          <option value="code:-1">番号 Z→A</option>
          <option value="mins:-1">片长 ↓</option>
          <option value="mins:1">片长 ↑</option>
          <option value="maker:1">厂商 A→Z</option>
          <option value="maker:-1">厂商 Z→A</option>
          {showActorSort && <option value="actor:1">人物 A→Z</option>}
        </select>
        <button className={`btn ${s.mergeBD ? 'on' : ''}`} onClick={s.toggleMergeBD}>合并 BD 重复版</button>
        <button className="btn" onClick={s.resetFilters}>重置</button>
        {onExport && (
          <button className="btn btn-primary" onClick={onExport}>
            <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M12 4v11m0 0l-4-4m4 4l4-4M5 19h14" />
            </svg>
            导出 CSV
          </button>
        )}
      </div>
    </div>
  )
}

function MakerOpts({ baseRows }: { baseRows: WorkRow[] }) {
  const s = useFilterStore()
  const opts = makerCounts(baseRows).map(([name, count]) => ({ name, count }))
  return (
    <MultiSelect label="厂商" options={opts} picked={s.pickedMakers} onChange={ms => s.setMakers(ms)} />
  )
}

// web/src/components/FilterBar.vue
<template>
  <div class="card">
    <div class="head">
      <span class="label">厂商</span>
      <span class="tip-text">下拉搜索，可多选</span>
    </div>

    <MakerSelect />

    <div class="row tools">
      <input v-model="state.kw" type="search" placeholder="搜索番号…" class="search" />

      <select v-model="state.year">
        <option value="">全部年份</option>
        <option v-for="y in years" :key="y" :value="y">{{ y }} 年</option>
      </select>

      <select v-model.number="state.minLen">
        <option :value="0">全部时长</option>
        <option :value="120">≥120 分</option>
        <option :value="240">≥240 分</option>
        <option :value="480">≥480 分</option>
        <option :value="960">≥960 分</option>
      </select>

      <select v-model="state.sortKey">
        <option value="date">按发行</option>
        <option value="code">按番号</option>
        <option value="mins">按片长</option>
        <option value="maker">按厂商</option>
        <option value="actor">按人物</option>
      </select>

      <button :class="{ on: state.sortDir > 0 }" @click="state.sortDir = -state.sortDir">
        {{ state.sortDir > 0 ? '升序 ↑' : '降序 ↓' }}
      </button>

      <button :class="{ on: state.mergeBD }" @click="toggleMerge">合并 BD 重复版</button>
      <button @click="resetAll">重置</button>
    </div>
  </div>
</template>

<script setup>
import MakerSelect from './MakerSelect.vue'
import { years, state, resetAll } from '../store'

const toggleMerge = () => {
  state.mergeBD = !state.mergeBD
  state.limit = 100
}
</script>

<style scoped>
/* 入场动画会让每张卡片形成独立层叠上下文，必须显式提升层级，
   否则下拉面板会被排在后面的表格卡片盖住 */
.card { position: relative; z-index: 5; }

.head { display: flex; align-items: baseline; gap: 8px; margin-bottom: 10px; }
.head .label { margin: 0; }
.tip-text { font-size: 11.5px; color: var(--muted); }

.tools { margin-top: 12px; padding-top: 12px; border-top: 1px dashed var(--line); }

.search {
  padding-left: 32px;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='%238b94a7' stroke-width='2' stroke-linecap='round'%3E%3Ccircle cx='11' cy='11' r='7'/%3E%3Cpath d='M20 20l-3.5-3.5'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: 10px center;
  min-width: 170px;
  flex: 1 1 170px;
}

@media (max-width: 720px) {
  input[type="search"], select { flex: 1 1 45%; min-width: 130px; }
  .tools button { flex: 1 1 auto; }
}
</style>
